# Cluster configuration.
#
# WARNING: This configuration is for local development. Do not use it in a production deployment.
#
# This configuration supports basic configuration using environment variables or an .env file
# TODO: add Postgres, Valley, Supabase, Superset
