[project]
name = "backend-link"
version = "0.1.0"
description = "Cliente API e operacoes entre camadas com a camada Backend."
readme = "README.md"
authors = [
    { name = "gpupo", email = "g1mar@gpupo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "supabase>=2.15.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
