[project]
name = "warehouse_migrations"
version = "0.1.0"
description = "Alembic instance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.15.0",
    "sqlmodel>=0.0.24",
    "warehouse-objects",
]

[tool.uv.sources]
warehouse-objects = { workspace = true }
